baseUrl: ""
languageCode: "en-us"
title: "Chi"
theme: "anubis"
paginate: 10

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 1
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Chi"
  description: "Chi's personal website"
